'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'AL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.students': 'Students',
    'nav.attendance': 'Attendance',
    'nav.finance': 'Finance',
    'nav.settings': 'Settings',
    'nav.quizzes': 'Quizzes & Events',
    'nav.my_students': 'My Students',
    'nav.my_portal': 'My Portal',
    'nav.grades': 'Grades',
    'nav.invoices': 'Invoices',
    'nav.main_menu': 'Main Menu',
    'nav.system': 'System',
    'nav.roles': 'Roles',
    'nav.users': 'Users',
    'nav.logout': 'Logout',
    
    // Header
    'header.search': 'Search students, degrees, or invoices...',
    'header.new_enrollment': 'New Enrollment',
    'header.new': 'New',
    
    // Roles
    'role.admin': 'System Admin',
    'role.teacher': 'Teacher',
    'role.student': 'Student',
    
    // Dashboard
    'dash.overview': 'Overview',
    'dash.overview_desc': "Here's what's happening at Future Minds Academy today.",
    'dash.total_students': 'Total Students',
    'dash.active_programs': 'Active Degrees',
    'dash.avg_attendance': 'Avg. Attendance',
    'dash.monthly_revenue': 'Monthly Revenue',
    'dash.recent_enrollments': 'Recent Enrollments',
    'dash.view_all': 'View All',
    'dash.quick_actions': 'Quick Actions',
    'dash.generate_invoice': 'Generate Invoice',
    'dash.record_attendance': 'Record Attendance',
    'dash.add_program': 'Add Degree',

    // Common Table Headers
    'table.student': 'Student',
    'table.program': 'Degree',
    'table.status': 'Status',
    'table.date': 'Date',
    'table.payment': 'Payment',
    'table.action': 'Action',

    // Statuses
    'status.active': 'Active',
    'status.pending': 'Pending',
    'status.suspended': 'Suspended',
    'status.graduated': 'Graduated',
    'status.paid': 'Paid',
    'status.unpaid': 'Unpaid',
    'status.partial': 'Partial',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.late': 'Late',
    'status.unrecorded': 'Unrecorded',

    // Students Page
    'students.title': 'Manage Students',
    'students.desc': 'View, filter, and manage student profiles, admissions, and records.',
    'students.add_new': 'Add Student',
    'students.search': 'Search students by name, ID, or email...',
    'students.filter': 'Filter',
    'students.all_programs': 'All Degrees',
    'students.all_statuses': 'All Statuses',
    'students.enrollment_date': 'Enrollment Date',
    'students.new_registration': 'New Student Registration',
    'students.new_registration_desc': 'Register a new student and generate their contract.',
    'students.cancel': 'Cancel',
    'students.first_name': 'First Name',
    'students.last_name': 'Last Name',
    'students.email': 'Email Address',
    'students.phone': 'Phone Number',
    'students.parent_phone': "Parent's Phone (Optional)",
    'students.gender': 'Gender',
    'students.select_gender': 'Select Gender',
    'students.male': 'Male',
    'students.female': 'Female',
    'students.other': 'Other',
    'students.select_program': 'Select Degree',
    'students.doc_upload': 'Document Upload',
    'students.drag_drop': 'Drag and drop documents here, or click to browse',
    'students.doc_types': 'ID, Photo, Certificates (PDF, JPG, PNG)',
    'students.save_draft': 'Save as Draft',
    'students.register': 'Register Student',

    // Attendance Page
    'attendance.title': 'Attendance Overview',
    'attendance.desc': 'Monitor student participation across all degrees.',
    'attendance.calendar': 'Calendar',
    'attendance.daily_list': 'Daily List',
    'attendance.overall': 'Overall Attendance',
    'attendance.late_today': 'Late Arrivals Today',
    'attendance.low_participation': 'Low Participation Alerts',
    'attendance.search': 'Search students or degrees...',
    'attendance.student_info': 'Student Info',
    'attendance.overall_percent': 'Overall %',
    'attendance.today_status': "Today's Status",

    // Finance Page
    'finance.title': 'Financial Overview',
    'finance.desc': 'Manage invoices, track payments, and monitor revenue.',
    'finance.create_invoice': 'Create Invoice',
    'finance.total_collected': 'Total Collected',
    'finance.pending_payments': 'Pending Payments',
    'finance.overdue_amount': 'Overdue Amount',
    'finance.search': 'Search invoices by ID or student name...',
    'finance.invoice_id': 'Invoice ID',
    'finance.amount': 'Amount',
    'finance.due_date': 'Due Date',

    // Teacher Dashboard
    'teacher.portal': 'Teacher Portal',
    'teacher.desc': 'Manage your classes, assignments, and student progress.',
    'teacher.create_quiz': 'Create Quiz / Event',
    'teacher.upcoming_classes': 'Upcoming Classes',
    'teacher.avg_class_grade': 'Avg. Class Grade',
    'teacher.active_quizzes': 'Active Quizzes',
    'teacher.recent_quizzes': 'Recent Quizzes & Assignments',
    'teacher.recent_grades': 'Recent Grades',
    'teacher.title_program': 'Title & Degree',
    'teacher.submissions': 'Submissions',
    'teacher.due_date': 'Due Date',
    'teacher.grade_submissions': 'Grade Submissions',
    'teacher.message_class': 'Message Class',
    'teacher.new_quiz': 'New Quiz / Event',
    'teacher.new_quiz_desc': 'Create a new assessment or schedule an event for your classes.',
    'teacher.cancel': 'Cancel',
    'teacher.title': 'Title',
    'teacher.type': 'Type',
    'teacher.select_type': 'Select Type',
    'teacher.quiz': 'Quiz',
    'teacher.assignment': 'Assignment',
    'teacher.event': 'Event',
    'teacher.program': 'Degree',
    'teacher.select_program': 'Select Degree',
    'teacher.date': 'Date',
    'teacher.time': 'Time',
    'teacher.duration': 'Duration (Minutes)',
    'teacher.max_score': 'Maximum Score',
    'teacher.description': 'Description',
    'teacher.save_draft': 'Save Draft',
    'teacher.publish': 'Publish',

    // Student Dashboard
    'student.welcome': 'Welcome back',
    'student.desc': 'Here is your academic and financial overview.',
    'student.overall_grade': 'Overall Grade',
    'student.attendance': 'Attendance',
    'student.active_courses': 'Active Courses',
    'student.next_payment': 'Next Payment',
    'student.recent_grades': 'Recent Grades & Quizzes',
    'student.assessment': 'Assessment',
    'student.score': 'Score',
    'student.my_invoices': 'My Invoices',

    // New Pages & Modals
    'teacher.total_students': 'Total Students',
    'teacher.avg_grade': 'Average Grade',
    'status.grading': 'Grading',
    'status.completed': 'Completed',
    'status.scheduled': 'Scheduled',
    'nav.announcements': 'Announcements',
    'nav.programs': 'Degrees',
    'announcements.title': 'Announcements',
    'announcements.desc': 'Stay updated with the latest news and events.',
    'announcements.new': 'New Announcement',
    'announcements.msg_title': 'Title',
    'announcements.message': 'Message',
    'announcements.audience': 'Target Audience',
    'announcements.publish': 'Publish Announcement',
    'programs.title': 'Degrees & Courses',
    'programs.desc': 'Manage academic degrees, pricing, and assignments.',
    'programs.new': 'New Degree',
    'programs.name': 'Degree Name',
    'programs.price': 'Price ($)',
    'programs.duration': 'Duration (Months)',
    'programs.save': 'Save Degree',
    'settings.profile': 'Profile Settings',
    'settings.avatar': 'Avatar Image URL',
    'settings.save': 'Save Changes',
    'settings.title': 'System Settings',
    'settings.desc': 'Manage your institution\'s preferences and configurations.',
    'settings.general': 'General',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.data': 'Data & Privacy',
    'settings.inst_profile': 'Institution Profile',
    'settings.inst_name': 'Institution Name',
    'settings.contact_email': 'Contact Email',
    'settings.phone': 'Phone Number',
    'settings.timezone': 'Timezone',
    'settings.branding': 'Branding',
    'settings.change_logo': 'Change Logo',
    'payment.title': 'Payment Instructions',
    'payment.desc': 'To complete this payment, please visit our administration office or contact us via email.',
    'payment.address': 'Address',
    'payment.email': 'Email',
    'payment.close': 'Close',
    'teacher.grade_modal_title': 'Grade Submissions',
    'teacher.grade_modal_desc': 'Enter scores for student submissions.',
    'teacher.save_grades': 'Save Grades',
    'student.overall_avg': 'Overall Average',
    'student.assessments_completed': 'Assessments Completed',
    'student.current_grade': 'Current Grade',
    'student.total_paid': 'Total Paid',
    'student.pending_balance': 'Pending Balance',
    'student.next_due': 'Next Payment Due',
    'student.pay_now': 'Pay Now',
    
    // Login Page
    'login.reset_title': 'Reset Password',
    'login.welcome_title': 'Welcome back',
    'login.reset_subtitle': 'Enter your email and we\'ll send you a secure access link.',
    'login.login_subtitle': 'Enter your credentials to access the portal.',
    'login.reset_success': 'If that email exists in our system, a secure reset link has been sent. Check your inbox — it expires in 1 hour.',
    'login.back_signin': 'Back to Sign In',
    'login.email_label': 'Email Address',
    'login.password_label': 'Password',
    'login.forgot': 'Forgot?',
    'login.sending': 'Sending…',
    'login.send_reset': 'Send Reset Link',
    'login.signin_loading': 'Signing In...',
    'login.signin_button': 'Sign In to Portal',
    'login.passkey': 'Sign in with Passkey',
    'login.error_email': 'Please enter a valid email address.',
    'login.error_password': 'Password must be at least 8 characters.',
    'login.error_login': 'Login failed. Please try again.',
    
    // New Additions (Profile, Export, FAQ, Command Palette)
    'profile.title': 'Student Profile',
    'profile.desc': 'Detailed view of student academic and financial records.',
    'profile.personal_info': 'Personal Information',
    'profile.academic_info': 'Academic Information',
    'profile.financial_info': 'Financial Information',
    'profile.enrollment_date': 'Enrollment Date',
    'profile.program': 'Degree',
    'profile.status': 'Status',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.back': 'Back to Students',
    'profile.edit': 'Edit Profile',
    'profile.attendance_rate': 'Attendance Rate',
    'profile.current_grade': 'Current Grade',
    'profile.total_invoiced': 'Total Invoiced',
    'profile.total_paid': 'Total Paid',
    'profile.outstanding_balance': 'Outstanding Balance',
    'action.export': 'Export',
    'action.export_csv': 'Export to CSV',
    'action.export_pdf': 'Export to PDF',
    'faq.title': 'Help & FAQ',
    'faq.search_q': 'How do I search quickly?',
    'faq.search_a': 'Press Cmd + K (or Ctrl+K on Windows) anywhere in the app to open the Command Palette. You can jump to any page instantly.',
    'faq.profile_q': 'How do I view a student\'s full profile?',
    'faq.profile_a': 'Click on any student row in the Students table to open their quick-view panel. From there, you can click "View Full Profile" to see all their details.',
    'faq.export_q': 'Can I export data?',
    'faq.export_a': 'Yes! Look for the "Export" button on the Students, Finance, and Attendance pages to download a CSV or PDF report.',
    'faq.select_q': 'How do I select multiple students?',
    'faq.select_a': 'Use the checkboxes on the left side of the Students table to select multiple records for bulk actions.',
    'cmd.placeholder': 'Type a command or search...',
    'cmd.quick_actions': 'Quick Actions',
    'cmd.no_results': 'No results found for',
    'cmd.navigate': 'to navigate',
    'cmd.close': 'to close',
    'dash.needs_attention': 'Needs Attention',
    'dash.pending_apps': 'Pending Applications',
    'dash.overdue_inv': 'Overdue Invoices',
    'dash.at_risk': 'Students at Risk (Attendance)',

    // Registration Applications
    'registrations.title': 'Registration Applications',
    'registrations.desc': 'Review and approve registration requests',
    'registrations.approve': 'Approve Application',
    'registrations.reject': 'Reject',
    'registrations.role': 'Role',
    'registrations.parent_name': "Parent's First Name",
    'registrations.program': 'Degree',
    'registrations.confirm_approve': 'Confirm Approval',
    'registrations.confirm_approve_msg': 'This will create a new user account and enroll them in the selected degree.',
    'registrations.confirm_reject': 'Confirm Rejection',
    'registrations.reject_reason': 'Reason for Rejection',
    'registrations.reject_reason_placeholder': 'Enter rejection reason (optional)...',
    'registrations.cancel': 'Cancel',
    'registrations.processing': 'Processing...',

    // Calendar
    'nav.calendar': 'Calendar',
    'cal.title': 'Calendar',
    'cal.desc': 'Schedule meetings and manage your events.',
    'cal.new_event': 'New Event',
    'cal.today': 'Today',
    'cal.event_title': 'Event Title',
    'cal.title_placeholder': 'Enter event title...',
    'cal.description': 'Description',
    'cal.desc_placeholder': 'Add a description...',
    'cal.all_day': 'All Day',
    'cal.start': 'Start',
    'cal.end': 'End',
    'cal.color': 'Color',
    'cal.participants': 'Participants',
    'cal.email_placeholder': 'Add participant by email...',
    'cal.invalid_email': 'Please enter a valid email address',
    'cal.already_added': 'This person has already been added',
    'cal.user_not_found': 'No account found with this email',
    'cal.lookup_failed': 'Failed to look up user',
    'cal.create_event': 'Create Event',
    'cal.delete_event': 'Delete Event',
    'cal.audience': 'Audience',
    'cal.everyone': 'Everyone',
    'cal.all_admins': 'All Admins',
    'cal.all_teachers': 'All Teachers',
    'cal.custom': 'Custom',
    'cal.loading_participants': 'Loading participants...',
    'cal.class_event': 'Class',
    'cal.your_events': 'Your Events',
    'cal.teacher_desc': 'View your class schedule and manage personal events.',
    'cal.students_in_class': 'Students in Class',
    'cal.student_desc': 'View your class schedule and add personal notes.',
    'cal.add_note': 'Add Note',
    'cal.note': 'Note',
    'cal.note_placeholder': 'Write your note here...',
    'cal.save_note': 'Save Note',
    'cal.delete_note': 'Delete Note',
    'cal.personal_note': 'Personal Note',
    'cal.class_readonly': 'This class was scheduled by your teacher and cannot be removed.',
    'cal.organizer': 'Organizer',
    'cal.your_response': 'Your Response',
    'cal.rsvp_attending': 'Attending',
    'cal.rsvp_pending': 'Undecided',
    'cal.rsvp_declined': 'Declining',

    // Common utilities
    'common.edit': 'Edit',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.saving': 'Saving…',
    'common.save': 'Save',
    'common.save_changes': 'Save Changes',
    'common.clear_filters': 'Clear filters',
    'common.clear_all': 'Clear all',
    'common.none': 'None',
    'common.loading': 'Loading…',
    'common.export_csv': 'Export CSV',
    'common.export': 'Export',
    'common.all': 'All',
    'common.filtering_by': 'Filtering by:',
    'common.no_records': 'No records found.',
    'common.back': 'Back',
    'common.processing': 'Processing…',
    'common.remove': 'Remove',
    'common.assign': 'Assign',
    'common.change': 'Change',
    'common.create': 'Create',
    'common.add_note': 'Add note',
    'common.add': 'Add',
    'common.optional': 'optional',

    // Table header additions
    'table.actions': 'Actions',
    'table.class': 'Class',
    'table.teacher': 'Teacher',
    'table.result': 'Result',
    'table.note': 'Note',
    'table.rate': 'Rate',
    'table.month': 'Month',
    'table.year': 'Year',
    'table.col_title': 'Title',
    'table.name': 'Name',

    // Status additions
    'status.not_paid': 'Not Paid',
    'status.overdue': 'Overdue',
    'status.passed': 'Passed',
    'status.failed': 'Failed',
    'status.not_graded': 'Not graded',

    // Month names (full)
    'months.january': 'January',
    'months.february': 'February',
    'months.march': 'March',
    'months.april': 'April',
    'months.may': 'May',
    'months.june': 'June',
    'months.july': 'July',
    'months.august': 'August',
    'months.september': 'September',
    'months.october': 'October',
    'months.november': 'November',
    'months.december': 'December',
    // Month names (short)
    'months.jan': 'Jan',
    'months.feb': 'Feb',
    'months.mar': 'Mar',
    'months.apr': 'Apr',
    'months.may_s': 'May',
    'months.jun': 'Jun',
    'months.jul': 'Jul',
    'months.aug': 'Aug',
    'months.sep': 'Sep',
    'months.oct': 'Oct',
    'months.nov': 'Nov',
    'months.dec': 'Dec',

    // Grades (admin grades page)
    'grades.desc': 'All grade tables across teachers and classes.',
    'grades.search': 'Search tables, classes, teachers...',
    'grades.all_teachers': 'All teachers',
    'grades.all_degrees': 'All degrees',
    'grades.stat_tables': 'Tables',
    'grades.stat_students': 'Students',
    'grades.stat_graded': 'Graded',
    'grades.stat_passed': 'Passed',
    'grades.stat_failed': 'Failed',
    'grades.empty_filtered': 'No grade tables match your filters.',
    'grades.empty': 'No grade tables created yet.',
    'grades.not_graded': 'Not graded',
    'grades.editing_for': 'Editing grade for',
    'grades.points_label': 'Points (1–100)',
    'grades.pass': 'Pass',
    'grades.fail': 'Fail',
    'grades.note_label': 'Note',
    'grades.note_optional': 'optional · visible to student',
    'grades.note_placeholder': 'Add a note for the student...',
    'grades.error_points': 'Points must be between 1 and 100.',
    'grades.error_result': 'Please select Pass or Fail.',
    'grades.error_save': 'Save failed. Please try again.',

    // Student page additions
    'student.grades_desc': 'Your final project grades and assessment results.',
    'student.stat_grade_tables': 'Grade Tables',
    'student.grades_search': 'Search grades...',
    'student.grade_filter_all': 'All Results',
    'student.grade_filter_all_classes': 'All Classes',
    'student.grade_filter_all_teachers': 'All Teachers',
    'student.grades_loading': 'Loading grades...',
    'student.grades_empty_filtered': 'No grades match your filters.',
    'student.grades_empty': 'No grades recorded yet.',
    'student.grades_not_graded': 'Not graded',
    'student.no_grades': 'No grades yet',
    'student.no_invoices': 'No invoices yet',
    'student.grade_excellent': 'Excellent',
    'student.grade_good': 'Good',
    'student.grade_needs_improvement': 'Needs Improvement',
    'student.due_in_days': 'Due in {n} days',
    'student.due_today': 'Due today',
    'student.days_overdue': '{n} days overdue',
    'student.invoices_desc': 'View your tuition invoices and payment status.',
    'student.invoices_search': 'Search invoices...',
    'student.invoices_all': 'All',
    'student.invoices_all_months': 'All Months',
    'student.invoices_all_years': 'All Years',
    'student.invoices_empty_filtered': 'No invoices match your filters.',
    'student.invoices_empty': 'No invoices yet.',

    // Teacher page additions
    'teacher.students_desc': 'Students enrolled in your classes.',
    'teacher.students_search': 'Search by name, email or class…',
    'teacher.students_empty_filtered': 'No students match your filters.',
    'teacher.students_empty': 'No students enrolled in your classes yet.',
    'teacher.attendance_breakdown': 'Attendance Breakdown',
    'teacher.note_for': 'Note for',
    'teacher.save_note': 'Save Note',
    'teacher.add_note': 'Add note',
    'teacher.all_payments': 'All Payments',
    'teacher.all_classes_filter': 'All Classes',
    'teacher.no_grades': 'No grades yet',
    'teacher.this_week': 'This week',
    'teacher.all_classes_trend': 'All classes',
    'teacher.grade_submissions_desc': 'Review and grade students',
    'teacher.record_attendance_desc': 'Mark daily class attendance',
    'teacher.message_class_desc': 'Send an announcement',
    'teacher.col_attendance': 'Attendance',
    'teacher.col_payments': 'Payments',
    'teacher.col_avg_grade': 'Avg. Grade',
    'teacher.col_notes': 'Notes',

    // Attendance page additions
    'attendance.overview': 'Attendance Overview',
    'attendance.export': 'Export',
    'attendance.search_placeholder': 'Search class or teacher…',
    'attendance.all_months': 'All Months',
    'attendance.all_years': 'All Years',
    'attendance.all_classes': 'All Classes',
    'attendance.filtering_by': 'Filtering by:',
    'attendance.col_date': 'Date',
    'attendance.col_class': 'Class',
    'attendance.col_rate': 'Rate',
    'attendance.col_present': 'Present',
    'attendance.col_late': 'Late',
    'attendance.col_absent': 'Absent',
    'attendance.no_records': 'No attendance records found.',
    'attendance.low_alert': 'Low participation alert',

    // Finance page additions
    'finance.all': 'All',
    'finance.all_months': 'All Months',
    'finance.all_years': 'All Years',
    'finance.all_classes': 'All Classes',
    'finance.all_teachers': 'All Teachers',
    'finance.col_student': 'Student',
    'finance.col_title': 'Title',
    'finance.col_class': 'Class',
    'finance.col_teacher': 'Teacher',
    'finance.col_month': 'Month',
    'finance.col_year': 'Year',

    // Nav additions
    'nav.registrations': 'Registrations',
    'nav.my_classes': 'My Classes',
    'nav.grading': 'Grading',

    // Layout
    'layout.notifications': 'Notifications',
    'layout.loading': 'Loading…',
    'layout.no_announcements': 'No announcements yet',
    'layout.view_all_announcements': 'View all announcements ?',
    'layout.announcement_count': '{n} announcement(s)',
    'layout.help_faq': 'Help & FAQ',

    // Command palette additions
    'cmd.action_dashboard': 'Go to Dashboard',
    'cmd.action_settings': 'Settings',
    'cmd.action_students': 'Manage Students',
    'cmd.action_finance': 'View Finance',
    'cmd.action_attendance': 'Attendance',
    'cmd.action_my_students': 'My Students',
    'cmd.action_my_classes': 'My Classes',
    'cmd.action_my_grades': 'My Grades',
    'cmd.action_my_invoices': 'My Invoices',
    'cmd.action_my_profile': 'My Profile',

    // Students manual enrollment form
    'students.manual_enrollment': 'Manual Enrollment',
    'students.manual_enrollment_desc': 'Create and immediately activate a student account.',
    'students.first_name_req': 'First Name *',
    'students.last_name_req': 'Last Name *',
    'students.parent_first_name_req': "Parent's First Name *",
    'students.email_req': 'Email Address *',
    'students.phone_req': 'Phone Number *',
    'students.secondary_phone_opt': 'Secondary Phone (Optional)',
    'students.location_req': 'Location *',
    'students.initial_password': 'Initial Password *',
    'students.password_hint': 'Students must change this password on first login.',
    'students.select_degree_req': 'Select Degree *',
    'students.select_class_req': 'Select Class *',
    'students.select_degree_first': 'Select degree first',
    'students.loading_classes': 'Loading classes...',
    'students.select_class_ph': 'Select Class',
    'students.select_location': 'Select Location',
    'students.select_degree_ph': 'Select Degree',
    'students.enrollment_success': 'Enrollment Successful',
    'students.enrollment_success_msg': 'has been enrolled and their account is active.',
    'students.temp_password': 'Temporary password:',
    'students.password_change_hint': 'The student will be required to change this password on first login.',
    'students.enroll_another': 'Enroll Another',
    'students.back_to_list': 'Back to Students',
    'students.enrollment_failed': 'Enrollment failed. Please try again.',
    'students.no_classes_found': 'No classes found',
    'students.all_locations': 'All Locations',
    'students.import_csv': 'Import CSV',
    'students.importing': 'Importing...',
    'students.enroll_student': 'Enroll Student',
    'students.enrolling': 'Enrolling...',
    'students.err_first_name': 'First name is required.',
    'students.err_last_name': 'Last name is required.',
    'students.err_parent': "Parent's first name is required.",
    'students.err_email': 'Please enter a valid email address.',
    'students.err_phone': 'Phone number is required.',
    'students.err_location': 'Please select a location.',
    'students.err_program': 'Please select a degree.',
    'students.err_class': 'Please select a class for this degree.',

    // Programs page (admin)
    'programs.degrees_title': 'Degrees',
    'programs.degrees_desc': 'Manage degrees, create classes, and assign teachers & students.',
    'programs.new_degree': 'New Degree',
    'programs.empty': 'No degrees created yet.',
    'programs.edit_degree': 'Edit Degree',
    'programs.degree_name_req': 'Degree Name *',
    'programs.degree_name_ph': 'e.g., Web Development',
    'programs.description': 'Description',
    'programs.description_ph': 'Brief description of the degree...',
    'programs.duration_mo': 'Duration (mo)',
    'programs.price_eur': 'Price (€)',
    'programs.capacity': 'Capacity',
    'programs.saving': 'Saving…',
    'programs.create_degree': 'Create Degree',
    'programs.save_changes': 'Save Changes',
    'programs.manage_classes': 'Manage classes for this degree',
    'programs.new_class': 'New Class',
    'programs.col_class_name': 'Class Name',
    'programs.col_teacher': 'Teacher',
    'programs.col_students_num': 'Number of Students',
    'programs.col_schedule': 'Schedule',
    'programs.col_degree': 'Degree',
    'programs.col_action': 'Action',
    'programs.edit': 'Edit',
    'programs.remove': 'Remove',
    'programs.cancel_edit': 'Cancel Edit',
    'programs.edit_class': 'Edit Class',
    'programs.no_teacher': 'No teacher assigned',
    'programs.weekly_sessions': 'Weekly Sessions',
    'programs.enrolled_students': 'Enrolled Students',
    'programs.add_student': 'Add Student',
    'programs.no_students': 'No students enrolled yet',
    'programs.create_class': 'Create Class',
    'programs.class_title': 'Class Title',
    'programs.assign_teacher': 'Assign Teacher',
    'programs.add_session': 'Add Session',
    'programs.select_class': 'Select a class…',
    'programs.available_students': 'Available Students',
    'programs.no_available': 'No available students',
    'programs.save_class': 'Save Class',
    'programs.select_teacher': 'Select Teacher',
    'programs.no_classes_degree': 'No classes found for this degree...',
    'programs.back_to_classes': '? Back to Classes',
    'programs.day_monday': 'Monday',
    'programs.day_tuesday': 'Tuesday',
    'programs.day_wednesday': 'Wednesday',
    'programs.day_thursday': 'Thursday',
    'programs.day_friday': 'Friday',
    'programs.day_saturday': 'Saturday',
    'programs.day_sunday': 'Sunday',
    'programs.duration_label': 'Duration: {n} months',
    'programs.price_label': 'Price: €{n}',
    'programs.capacity_label': 'Capacity: {n} students',
    'programs.not_assigned': 'Not assigned',
    'programs.select_teacher_ph': 'Select a teacher...',
    'programs.creating': 'Creating...',
    'programs.class_title_ph': 'e.g., Web Dev - Batch 1',
    'programs.no_classes': 'No classes created yet',
    'programs.empty_hint': 'No degrees created yet. Click "New Degree" to get started.',

    // Registration applications additions
    'registrations.all': 'All',
    'registrations.pending_filter': 'Pending',
    'registrations.approved_filter': 'Approved',
    'registrations.rejected_filter': 'Rejected',
    'registrations.archived': 'Archived',
    'registrations.archive': 'Archive',
    'registrations.unarchive': 'Unarchive',
    'registrations.applied': 'Applied:',
    'registrations.secondary_phone': 'Secondary Phone',
    'registrations.location': 'Location',
    'registrations.id_document': 'ID Document',
    'registrations.view_document': 'View Document',
    'registrations.date_of_birth': 'Date of Birth',
    'registrations.address': 'Address',
    'registrations.emergency_contact': 'Emergency Contact',
    'registrations.emergency_phone': 'Emergency Phone',
    'registrations.specialization': 'Specialization',
    'registrations.qualifications': 'Qualifications',
    'registrations.experience': 'Years of Experience',
    'registrations.years': 'years',
    'registrations.admin_notes': 'Admin Notes',
    'registrations.assign_class': 'Assign to Class',
    'registrations.loading_classes': 'Loading classes…',
    'registrations.no_classes': 'No classes found for this degree...',
    'registrations.select_class': 'Select a class…',
    'registrations.this_app_archived': 'This application is archived. Unarchiving will restore it to pending status.',
    'registrations.no_applications': 'No applications found.',
    'registrations.failed_approve': 'Failed to approve application',
    'registrations.failed_reject': 'Failed to reject application',
    'registrations.failed_archive': 'Failed to archive application',
    'registrations.failed_unarchive': 'Failed to unarchive application',

    // Settings additions
    'settings.platform': 'Platform Settings',
    'settings.file_too_large': 'File too large. Maximum 2 MB.',
    'settings.file_type': 'Only JPG, PNG, GIF, or WebP files allowed.',
    'settings.upload_success': 'Profile picture uploaded.',
    'settings.upload_failed': 'Upload failed.',
    'settings.pw_too_short': 'Password must be at least 6 characters.',
    'settings.pw_mismatch': 'Passwords do not match.',
    'settings.profile_saved': 'Profile saved.',
    'settings.platform_saved': 'Platform settings saved.',
    'settings.save_failed': 'Failed to save.',
    'settings.profile_section': 'My Profile',
    'settings.profile_desc': 'Manage your personal information and preferences.',
    'settings.email_username': 'Email (Username)',
    'settings.file_hints': 'JPG, PNG, GIF, or WebP · Max 2 MB',
    'settings.change_password': 'Change Password',
    'settings.new_password': 'New Password',
    'settings.confirm_password': 'Confirm Password',
    'settings.password_hint': 'Minimum 6 characters. Leave blank to keep current password.',
    'settings.logo_url': 'Logo URL',
    'settings.logo_hint': 'Recommended size: 512x512px (PNG or SVG)',
    'settings.contact_info': 'Contact Information',
    'settings.primary_phone': 'Primary Phone',
    'settings.secondary_phone': 'Secondary Phone',
    'settings.open_hours': 'Open Hours',
    'settings.address': 'Address',
    'settings.data_export': 'Data Export',
    'settings.data_export_desc': 'Download your institution data as Excel-compatible CSV files.',
    'settings.export_profiles': 'User Profiles',
    'settings.export_enrollments': 'Student Enrollments',
    'settings.export_attendance': 'Attendance Records',
    'settings.export_invoices': 'Invoices',
    'settings.export_grades': 'Grade Entries',
    'settings.upload_photo': 'Upload Photo',
    'settings.uploading': 'Uploading…',
    'settings.no_data_found': 'No data found.',
    'settings.exported': 'Exported successfully.',
    'settings.export_failed': 'Export failed.',
    'settings.messages': 'Message Templates',
    'settings.messages_desc': 'Customize SMS notifications sent to students and staff.',
    'settings.sms_templates': 'SMS Templates',
    'settings.template_vars': 'Available variables:',
    'settings.template_saved': 'Template saved!',
  },
  AL: {
    // Navigation
    'nav.dashboard': 'Pulti',
    'nav.students': 'Studentët',
    'nav.attendance': 'Pjesëmarrja',
    'nav.finance': 'Financa',
    'nav.settings': 'Cilësimet',
    'nav.quizzes': 'Kuize & Evente',
    'nav.my_students': 'Studentët e mi',
    'nav.my_portal': 'Portali im',
    'nav.grades': 'Notat',
    'nav.invoices': 'Faturat',
    'nav.main_menu': 'Menyja Kryesore',
    'nav.system': 'Sistemi',
    'nav.roles': 'Rolet',
    'nav.users': 'Përdoruesit',
    'nav.logout': 'Dil',
    
    // Header
    'header.search': 'Kërko studentë, diploma, ose fatura...',
    'header.new_enrollment': 'Regjistrim i Ri',
    'header.new': 'I Ri',
    
    // Roles
    'role.admin': 'Administrator',
    'role.teacher': 'Mësues',
    'role.student': 'Student',
    
    // Dashboard
    'dash.overview': 'Përmbledhje',
    'dash.overview_desc': "Ja çfarë po ndodh në Future Minds Academy sot.",
    'dash.total_students': 'Totali i Studentëve',
    'dash.active_programs': 'Diploma Aktive',
    'dash.avg_attendance': 'Pjesëmarrja Mesatare',
    'dash.monthly_revenue': 'Të Ardhurat Mujore',
    'dash.recent_enrollments': 'Regjistrimet e Fundit',
    'dash.view_all': 'Shiko të Gjitha',
    'dash.quick_actions': 'Veprime të Shpejta',
    'dash.generate_invoice': 'Gjenero Faturë',
    'dash.record_attendance': 'Shëno Pjesëmarrjen',
    'dash.add_program': 'Shto Diplomë',

    // Common Table Headers
    'table.student': 'Studenti',
    'table.program': 'Diploma',
    'table.status': 'Statusi',
    'table.date': 'Data',
    'table.payment': 'Pagesa',
    'table.action': 'Veprimi',

    // Statuses
    'status.active': 'Aktiv',
    'status.pending': 'Në Pritje',
    'status.suspended': 'Pezulluar',
    'status.graduated': 'I Diplomuar',
    'status.paid': 'Paguar',
    'status.unpaid': 'E Papaguar',
    'status.partial': 'Pjesërisht',
    'status.present': 'Prezent',
    'status.absent': 'Mungesë',
    'status.late': 'Vonesë',
    'status.unrecorded': 'Nuk u Regjistrua',

    // Students Page
    'students.title': 'Menaxho Studentët',
    'students.desc': 'Shiko, filtro dhe menaxho profilet e studentëve, pranimet dhe të dhënat.',
    'students.add_new': 'Shto Student',
    'students.search': 'Kërko studentë sipas emrit, ID, ose emailit...',
    'students.filter': 'Filtro',
    'students.all_programs': 'Të Gjitha Diplomat',
    'students.all_statuses': 'Të Gjitha Statuset',
    'students.enrollment_date': 'Data e Regjistrimit',
    'students.new_registration': 'Regjistrim i Ri Studenti',
    'students.new_registration_desc': 'Regjistro një student të ri dhe gjenero kontratën e tyre.',
    'students.cancel': 'Anulo',
    'students.first_name': 'Emri',
    'students.last_name': 'Mbiemri',
    'students.email': 'Adresa e Emailit',
    'students.phone': 'Numri i Telefonit',
    'students.parent_phone': "Telefoni i Prindit (Opsionale)",
    'students.gender': 'Gjinia',
    'students.select_gender': 'Zgjidh Gjininë',
    'students.male': 'Mashkull',
    'students.female': 'Femër',
    'students.other': 'Tjetër',
    'students.select_program': 'Zgjidh Diplomën',
    'students.doc_upload': 'Ngarkimi i Dokumenteve',
    'students.drag_drop': 'Tërhiq dhe lësho dokumentet këtu, ose kliko për të shfletuar',
    'students.doc_types': 'ID, Foto, Çertifikata (PDF, JPG, PNG)',
    'students.save_draft': 'Ruaj si Draft',
    'students.register': 'Regjistro Studentin',

    // Attendance Page
    'attendance.title': 'Përmbledhja e Pjesëmarrjes',
    'attendance.desc': 'Monitoro pjesëmarrjen e studentëve në të gjitha diplomat.',
    'attendance.calendar': 'Kalendari',
    'attendance.daily_list': 'Lista Ditore',
    'attendance.overall': 'Pjesëmarrja e Përgjithshme',
    'attendance.late_today': 'Vonesat Sot',
    'attendance.low_participation': 'Alarme për Pjesëmarrje të Ulët',
    'attendance.search': 'Kërko studentë ose diploma...',
    'attendance.student_info': 'Info e Studentit',
    'attendance.overall_percent': '% e Përgjithshme',
    'attendance.today_status': "Statusi i Sotëm",

    // Finance Page
    'finance.title': 'Përmbledhja Financiare',
    'finance.desc': 'Menaxho faturat, gjurmo pagesat dhe monitoro të ardhurat.',
    'finance.create_invoice': 'Krijo Faturë',
    'finance.total_collected': 'Totali i Mbledhur',
    'finance.pending_payments': 'Pagesat në Pritje',
    'finance.overdue_amount': 'Shuma e Vonuar',
    'finance.search': 'Kërko fatura sipas ID ose emrit të studentit...',
    'finance.invoice_id': 'ID e Faturës',
    'finance.amount': 'Shuma',
    'finance.due_date': 'Data e Skadimit',

    // Teacher Dashboard
    'teacher.portal': 'Portali i Mësuesit',
    'teacher.desc': 'Menaxho klasat, detyrat dhe progresin e studentëve.',
    'teacher.create_quiz': 'Krijo Kuiz / Event',
    'teacher.upcoming_classes': 'Klasat e Ardhshme',
    'teacher.avg_class_grade': 'Nota Mesatare e Klasës',
    'teacher.active_quizzes': 'Kuize Aktive',
    'teacher.recent_quizzes': 'Kuizet & Detyrat e Fundit',
    'teacher.recent_grades': 'Notat e Fundit',
    'teacher.title_program': 'Titulli & Diploma',
    'teacher.submissions': 'Dorëzimet',
    'teacher.due_date': 'Data e Skadimit',
    'teacher.grade_submissions': 'Vlerëso Dorëzimet',
    'teacher.message_class': 'Dërgo Mesazh Klasës',
    'teacher.new_quiz': 'Kuiz / Event i Ri',
    'teacher.new_quiz_desc': 'Krijo një vlerësim të ri ose planifiko një event për klasat e tua.',
    'teacher.cancel': 'Anulo',
    'teacher.title': 'Titulli',
    'teacher.type': 'Tipi',
    'teacher.select_type': 'Zgjidh Tipin',
    'teacher.quiz': 'Kuiz',
    'teacher.assignment': 'Detyrë',
    'teacher.event': 'Event',
    'teacher.program': 'Diploma',
    'teacher.select_program': 'Zgjidh Diplomën',
    'teacher.date': 'Data',
    'teacher.time': 'Koha',
    'teacher.duration': 'Kohëzgjatja (Minuta)',
    'teacher.max_score': 'Pikët Maksimale',
    'teacher.description': 'Përshkrimi',
    'teacher.save_draft': 'Ruaj Draft',
    'teacher.publish': 'Publiko',

    // Student Dashboard
    'student.welcome': 'Mirë se u ktheve',
    'student.desc': 'Këtu është përmbledhja juaj akademike dhe financiare.',
    'student.overall_grade': 'Nota e Përgjithshme',
    'student.attendance': 'Pjesëmarrja',
    'student.active_courses': 'Kurse Aktive',
    'student.next_payment': 'Pagesa e Radhës',
    'student.recent_grades': 'Notat & Kuizet e Fundit',
    'student.assessment': 'Vlerësimi',
    'student.score': 'Pikët',
    'student.my_invoices': 'Faturat e Mia',

    // New Pages & Modals
    'teacher.total_students': 'Totali i Studentëve',
    'teacher.avg_grade': 'Nota Mesatare',
    'status.grading': 'Në Vlerësim',
    'status.completed': 'Përfunduar',
    'status.scheduled': 'Planifikuar',
    'nav.announcements': 'Lajmërime',
    'nav.programs': 'Diplomat',
    'announcements.title': 'Lajmërime',
    'announcements.desc': 'Qëndroni të përditësuar me lajmet dhe eventet e fundit.',
    'announcements.new': 'Lajmërim i Ri',
    'announcements.msg_title': 'Titulli',
    'announcements.message': 'Mesazhi',
    'announcements.audience': 'Audienca',
    'announcements.publish': 'Publiko Lajmërimin',
    'programs.title': 'Diplomat & Kurset',
    'programs.desc': 'Menaxhoni diplomat akademike, çmimet dhe caktimet.',
    'programs.new': 'Diplomë e Re',
    'programs.name': 'Emri i Diplomës',
    'programs.price': 'Çmimi ($)',
    'programs.duration': 'Kohëzgjatja (Muaj)',
    'programs.save': 'Ruaj Diplomën',
    'settings.profile': 'Cilësimet e Profilit',
    'settings.avatar': 'URL e Fotos së Profilit',
    'settings.save': 'Ruaj Ndryshimet',
    'settings.title': 'Cilësimet e Sistemit',
    'settings.desc': 'Menaxhoni preferencat dhe konfigurimet e institucionit tuaj.',
    'settings.general': 'Të Përgjithshme',
    'settings.security': 'Siguria',
    'settings.notifications': 'Njoftimet',
    'settings.data': 'Të Dhënat & Privatësia',
    'settings.inst_profile': 'Profili i Institucionit',
    'settings.inst_name': 'Emri i Institucionit',
    'settings.contact_email': 'Emaili i Kontaktit',
    'settings.phone': 'Numri i Telefonit',
    'settings.timezone': 'Zona Kohore',
    'settings.branding': 'Marka',
    'settings.change_logo': 'Ndrysho Logon',
    'payment.title': 'Udhëzimet e Pagesës',
    'payment.desc': 'Për të përfunduar këtë pagesë, ju lutemi vizitoni zyrën tonë të administratës ose na kontaktoni përmes emailit.',
    'payment.address': 'Adresa',
    'payment.email': 'Email',
    'payment.close': 'Mbyll',
    'teacher.grade_modal_title': 'Vlerëso Dorëzimet',
    'teacher.grade_modal_desc': 'Vendosni pikët për dorëzimet e studentëve.',
    'teacher.save_grades': 'Ruaj Notat',
    'student.overall_avg': 'Mesatarja e Përgjithshme',
    'student.assessments_completed': 'Vlerësime të Përfunduara',
    'student.current_grade': 'Nota Aktuale',
    'student.total_paid': 'Totali i Paguar',
    'student.pending_balance': 'Bilanci në Pritje',
    'student.next_due': 'Pagesa e Radhës',
    'student.pay_now': 'Paguaj Tani',
    
    // Login Page
    'login.reset_title': 'Rivendos Fjalëkalimin',
    'login.welcome_title': 'Mirë se erdhe përsëri',
    'login.reset_subtitle': 'Fut email-in tënd dhe ne do të të dërgojmë një lidhje të sigurt qasje.',
    'login.login_subtitle': 'Fut kredencialet tuaja për të qasur portalin.',
    'login.reset_success': 'Nëse ai email ekziston në sistemin tonë, një lidhje sigure për rivendosje është dërguar. Kontrollo kutinë e ardhjes — skadon në 1 orë.',
    'login.back_signin': 'Kthehu në Hyrje',
    'login.email_label': 'Adresa Email',
    'login.password_label': 'Fjalëkalimi',
    'login.forgot': 'Harrua?',
    'login.sending': 'Duke dërguar…',
    'login.send_reset': 'Dërgo Lidhjen e Rivendosjes',
    'login.signin_loading': 'Duke hypur...',
    'login.signin_button': 'Hyj në Portal',
    'login.passkey': 'Hyj me Passkey',
    'login.error_email': 'Ju lutemi futni një adresë email të vlefshme.',
    'login.error_password': 'Fjalëkalimi duhet të jetë të paktën 8 karaktere.',
    'login.error_login': 'Hyrja dështoi. Ju lutemi provoni përsëri.',
    
    // New Additions (Profile, Export, FAQ, Command Palette)
    'profile.title': 'Profili i Studentit',
    'profile.desc': 'Pamje e detajuar e të dhënave akademike dhe financiare të studentit.',
    'profile.personal_info': 'Informacion Personal',
    'profile.academic_info': 'Informacion Akademik',
    'profile.financial_info': 'Informacion Financiar',
    'profile.enrollment_date': 'Data e Regjistrimit',
    'profile.program': 'Diploma',
    'profile.status': 'Statusi',
    'profile.email': 'Emaili',
    'profile.phone': 'Telefoni',
    'profile.address': 'Adresa',
    'profile.back': 'Kthehu te Studentët',
    'profile.edit': 'Ndrysho Profilin',
    'profile.attendance_rate': 'Përqindja e Pjesëmarrjes',
    'profile.current_grade': 'Nota Aktuale',
    'profile.total_invoiced': 'Totali i Faturuar',
    'profile.total_paid': 'Totali i Paguar',
    'profile.outstanding_balance': 'Bilanci i Papaguar',
    'action.export': 'Eksporto',
    'action.export_csv': 'Eksporto në CSV',
    'action.export_pdf': 'Eksporto në PDF',
    'faq.title': 'Ndihmë & Pyetje',
    'faq.search_q': 'Si mund të kërkoj shpejt?',
    'faq.search_a': 'Shtyp Cmd + K (ose Ctrl+K në Windows) kudo në aplikacion për të hapur Paletën e Komandave. Mund të kalosh në çdo faqe menjëherë.',
    'faq.profile_q': 'Si mund ta shoh profilin e plotë të një studenti?',
    'faq.profile_a': 'Kliko në çdo rresht studenti në tabelën e Studentëve për të hapur panelin e tyre të shpejtë. Nga aty, mund të klikosh "Shiko Profilin e Plotë" për të parë të gjitha detajet e tyre.',
    'faq.export_q': 'A mund të eksportoj të dhëna?',
    'faq.export_a': 'Po! Kërko butonin "Eksporto" në faqet e Studentëve, Financës dhe Pjesëmarrjes për të shkarkuar një raport CSV ose PDF.',
    'faq.select_q': 'Si mund të zgjedh disa studentë?',
    'faq.select_a': 'Përdor kutitë e zgjedhjes në anën e majtë të tabelës së Studentëve për të zgjedhur disa rekorde për veprime në grup.',
    'cmd.placeholder': 'Shkruaj një komandë ose kërko...',
    'cmd.quick_actions': 'Veprime të Shpejta',
    'cmd.no_results': 'Nuk u gjetën rezultate për',
    'cmd.navigate': 'për të naviguar',
    'cmd.close': 'për të mbyllur',
    'dash.needs_attention': 'Kërkon Vëmendje',
    'dash.pending_apps': 'Aplikime në Pritje',
    'dash.overdue_inv': 'Fatura të Vonuara',
    'dash.at_risk': 'Studentë në Rrezik (Pjesëmarrja)',

    // Registration Applications
    'registrations.title': 'Aplikime për Regjistrim',
    'registrations.desc': 'Shqyrto dhe mirato kërkesa për regjistrim',
    'registrations.approve': 'Mirato Aplikimin',
    'registrations.reject': 'Refuzo',
    'registrations.role': 'Roli',
    'registrations.parent_name': 'Emri i Prindit',
    'registrations.program': 'Diploma',
    'registrations.confirm_approve': 'Konfirmo Miratimin',
    'registrations.confirm_approve_msg': 'Kjo do të krijojë një llogari dhe do të regjistrojë studentin në diplomën e zgjedhur.',
    'registrations.confirm_reject': 'Konfirmo Refuzimin',
    'registrations.reject_reason': 'Arsyeja e Refuzimit',
    'registrations.reject_reason_placeholder': 'Shkruaj arsyen e refuzimit (opsionale)...',
    'registrations.cancel': 'Anulo',
    'registrations.processing': 'Duke procesuar...',

    // Calendar
    'nav.calendar': 'Kalendar',
    'cal.title': 'Kalendar',
    'cal.desc': 'Planifiko takime dhe menaxho ngjarjet tuaja.',
    'cal.new_event': 'Ngjarje e Re',
    'cal.today': 'Sot',
    'cal.event_title': 'Titulli i Ngjarjes',
    'cal.title_placeholder': 'Shkruaj titullin e ngjarjes...',
    'cal.description': 'Përshkrimi',
    'cal.desc_placeholder': 'Shto një përshkrim...',
    'cal.all_day': 'Gjatë Ditës',
    'cal.start': 'Fillimi',
    'cal.end': 'Mbarimi',
    'cal.color': 'Ngjyra',
    'cal.participants': 'Pjesëmarrësit',
    'cal.email_placeholder': 'Shto pjesëmarrës me email...',
    'cal.invalid_email': 'Ju lutemi vendosni një email të vlefshëm',
    'cal.already_added': 'Ky person është shtuar tashmë',
    'cal.user_not_found': 'Nuk u gjet asnjë llogari me këtë email',
    'cal.lookup_failed': 'Dështoi gjetja e përdoruesit',
    'cal.create_event': 'Krijo Ngjarje',
    'cal.delete_event': 'Fshi Ngjarjen',
    'cal.audience': 'Audience',
    'cal.everyone': 'Të gjithë',
    'cal.all_admins': 'Të gjithë adminët',
    'cal.all_teachers': 'Të gjithë mësuesit',
    'cal.custom': 'Me dëshirë',
    'cal.loading_participants': 'Po ngarkon pjesëmarrësit...',
    'cal.class_event': 'Klasë',
    'cal.your_events': 'Ngjarjet tuaja',
    'cal.teacher_desc': 'Shiko orarin e klasës dhe menaxho ngjarjet personale.',
    'cal.students_in_class': 'Studentët në Klasë',
    'cal.student_desc': 'Shiko orarin e klasës dhe shto shënime personale.',
    'cal.add_note': 'Shto Shënim',
    'cal.note': 'Shënim',
    'cal.note_placeholder': 'Shkruaj shënimin tënd këtu...',
    'cal.save_note': 'Ruaj Shënimin',
    'cal.delete_note': 'Fshi Shënimin',
    'cal.personal_note': 'Shënim Personal',
    'cal.class_readonly': 'Kjo klasë është planifikuar nga mësuesi juaj dhe nuk mund të hiqet.',
    'cal.organizer': 'Organizator',
    'cal.your_response': 'Përgjigja Juaj',
    'cal.rsvp_attending': 'Prezent',
    'cal.rsvp_pending': 'I Pasigurt',
    'cal.rsvp_declined': 'Refuzoj',

    // Common utilities
    'common.edit': 'Ndrysho',
    'common.cancel': 'Anulo',
    'common.submit': 'Dërgo',
    'common.saving': 'Duke ruajtur…',
    'common.save': 'Ruaj',
    'common.save_changes': 'Ruaj Ndryshimet',
    'common.clear_filters': 'Fshi filtrat',
    'common.clear_all': 'Fshi të gjitha',
    'common.none': 'Asnjë',
    'common.loading': 'Duke ngarkuar…',
    'common.export_csv': 'Eksporto CSV',
    'common.export': 'Eksporto',
    'common.all': 'Të gjitha',
    'common.filtering_by': 'Duke filtruar sipas:',
    'common.no_records': 'Nuk u gjetën të dhëna.',
    'common.back': 'Kthehu',
    'common.processing': 'Duke procesuar…',
    'common.remove': 'Hiq',
    'common.assign': 'Cakto',
    'common.change': 'Ndrysho',
    'common.create': 'Krijo',
    'common.add_note': 'Shto shënim',
    'common.add': 'Shto',
    'common.optional': 'opsional',

    // Table header additions
    'table.actions': 'Veprimet',
    'table.class': 'Klasa',
    'table.teacher': 'Mësuesi',
    'table.result': 'Rezultati',
    'table.note': 'Shënim',
    'table.rate': 'Shkalla',
    'table.month': 'Muaji',
    'table.year': 'Viti',
    'table.col_title': 'Titulli',
    'table.name': 'Emri',

    // Status additions
    'status.not_paid': 'E Papaguar',
    'status.overdue': 'E Vonuar',
    'status.passed': 'Kaloi',
    'status.failed': 'Dështoi',
    'status.not_graded': 'I pavlerësuar',

    // Month names (full)
    'months.january': 'Janar',
    'months.february': 'Shkurt',
    'months.march': 'Mars',
    'months.april': 'Prill',
    'months.may': 'Maj',
    'months.june': 'Qershor',
    'months.july': 'Korrik',
    'months.august': 'Gusht',
    'months.september': 'Shtator',
    'months.october': 'Tetor',
    'months.november': 'Nëntor',
    'months.december': 'Dhjetor',
    // Month names (short)
    'months.jan': 'Jan',
    'months.feb': 'Shk',
    'months.mar': 'Mar',
    'months.apr': 'Pri',
    'months.may_s': 'Maj',
    'months.jun': 'Qer',
    'months.jul': 'Kor',
    'months.aug': 'Gus',
    'months.sep': 'Sht',
    'months.oct': 'Tet',
    'months.nov': 'Nën',
    'months.dec': 'Dhj',

    // Grades (admin grades page)
    'grades.desc': 'Të gjitha tabelat e notave nëpër mësues dhe klasa.',
    'grades.search': 'Kërko tabela, klasa, mësues...',
    'grades.all_teachers': 'Të gjithë mësuesit',
    'grades.all_degrees': 'Të gjitha diplomat',
    'grades.stat_tables': 'Tabela',
    'grades.stat_students': 'Studentë',
    'grades.stat_graded': 'Vlerësuar',
    'grades.stat_passed': 'Kaluan',
    'grades.stat_failed': 'Dështuan',
    'grades.empty_filtered': 'Asnjë tabelë note nuk përputhet me filtrat tuaj.',
    'grades.empty': 'Asnjë tabelë note nuk është krijuar ende.',
    'grades.not_graded': 'I pavlerësuar',
    'grades.editing_for': 'Duke edituar notën për',
    'grades.points_label': 'Pikët (1–100)',
    'grades.pass': 'Kaloj',
    'grades.fail': 'Dështoj',
    'grades.note_label': 'Shënim',
    'grades.note_optional': 'opsional · i dukshëm për studentin',
    'grades.note_placeholder': 'Shto një shënim për studentin...',
    'grades.error_points': 'Pikët duhet të jenë midis 1 dhe 100.',
    'grades.error_result': 'Ju lutemi zgjidhni Kaloj ose Dështoj.',
    'grades.error_save': 'Ruajtja dështoi. Ju lutemi provoni sërish.',

    // Student page additions
    'student.grades_desc': 'Notat tuaja dhe rezultatet e vlerësimeve.',
    'student.stat_grade_tables': 'Tabela Notash',
    'student.grades_search': 'Kërko nota...',
    'student.grade_filter_all': 'Të gjitha',
    'student.grade_filter_all_classes': 'Të gjitha Klasat',
    'student.grade_filter_all_teachers': 'Të gjithë Mësuesit',
    'student.grades_loading': 'Duke ngarkuar notat...',
    'student.grades_empty_filtered': 'Asnjë notë nuk përputhet me filtrat tuaj.',
    'student.grades_empty': 'Asnjë notë nuk është regjistruar ende.',
    'student.grades_not_graded': 'I pavlerësuar',
    'student.no_grades': 'Asnjë notë ende',
    'student.no_invoices': 'Asnjë faturë ende',
    'student.grade_excellent': 'Shkëlqyeshëm',
    'student.grade_good': 'Mirë',
    'student.grade_needs_improvement': 'Nevojë për Përmirësim',
    'student.due_in_days': 'Afati në {n} ditë',
    'student.due_today': 'Afati sot',
    'student.days_overdue': '{n} ditë me vonesë',
    'student.invoices_desc': 'Shiko faturat tuaja dhe statusin e pagesave.',
    'student.invoices_search': 'Kërko fatura...',
    'student.invoices_all': 'Të gjitha',
    'student.invoices_all_months': 'Të gjithë Muajt',
    'student.invoices_all_years': 'Të gjitha Vitet',
    'student.invoices_empty_filtered': 'Asnjë faturë nuk përputhet me filtrat tuaj.',
    'student.invoices_empty': 'Asnjë faturë ende.',

    // Teacher page additions
    'teacher.students_desc': 'Studentët e regjistruar në klasat tuaja.',
    'teacher.students_search': 'Kërko sipas emrit, emailit ose klasës…',
    'teacher.students_empty_filtered': 'Asnjë student nuk përputhet me filtrat tuaj.',
    'teacher.students_empty': 'Asnjë student nuk është regjistruar në klasat tuaja ende.',
    'teacher.attendance_breakdown': 'Detajet e Pjesëmarrjes',
    'teacher.note_for': 'Shënim për',
    'teacher.save_note': 'Ruaj Shënimin',
    'teacher.add_note': 'Shto shënim',
    'teacher.all_payments': 'Të gjitha Pagesat',
    'teacher.all_classes_filter': 'Të gjitha Klasat',
    'teacher.no_grades': 'Asnjë notë ende',
    'teacher.this_week': 'Kjo javë',
    'teacher.all_classes_trend': 'Të gjitha klasat',
    'teacher.grade_submissions_desc': 'Shqyrto dhe vlerëso studentët',
    'teacher.record_attendance_desc': 'Shëno pjesëmarrjen ditore të klasës',
    'teacher.message_class_desc': 'Dërgo një lajmërim',
    'teacher.col_attendance': 'Pjesëmarrja',
    'teacher.col_payments': 'Pagesat',
    'teacher.col_avg_grade': 'Nota Mesatare',
    'teacher.col_notes': 'Shënime',

    // Attendance page additions
    'attendance.overview': 'Përmbledhja e Pjesëmarrjes',
    'attendance.export': 'Eksporto',
    'attendance.search_placeholder': 'Kërko klasën ose mësuesin…',
    'attendance.all_months': 'Të gjithë Muajt',
    'attendance.all_years': 'Të gjitha Vitet',
    'attendance.all_classes': 'Të gjitha Klasat',
    'attendance.filtering_by': 'Duke filtruar sipas:',
    'attendance.col_date': 'Data',
    'attendance.col_class': 'Klasa',
    'attendance.col_rate': 'Shkalla',
    'attendance.col_present': 'Prezent',
    'attendance.col_late': 'Vonuar',
    'attendance.col_absent': 'Munguar',
    'attendance.no_records': 'Nuk u gjetën të dhëna të pjesëmarrjes.',
    'attendance.low_alert': 'Alarm për pjesëmarrje të ulët',

    // Finance page additions
    'finance.all': 'Të gjitha',
    'finance.all_months': 'Të gjithë Muajt',
    'finance.all_years': 'Të gjitha Vitet',
    'finance.all_classes': 'Të gjitha Klasat',
    'finance.all_teachers': 'Të gjithë Mësuesit',
    'finance.col_student': 'Studenti',
    'finance.col_title': 'Titulli',
    'finance.col_class': 'Klasa',
    'finance.col_teacher': 'Mësuesi',
    'finance.col_month': 'Muaji',
    'finance.col_year': 'Viti',

    // Nav additions
    'nav.registrations': 'Regjistrimet',
    'nav.my_classes': 'Klasat e Mia',
    'nav.grading': 'Vlerësimet',

    // Layout
    'layout.notifications': 'Njoftimet',
    'layout.loading': 'Duke ngarkuar…',
    'layout.no_announcements': 'Asnjë lajmërim ende',
    'layout.view_all_announcements': 'Shiko të gjitha lajmërimet ?',
    'layout.announcement_count': '{n} lajmërim(e)',
    'layout.help_faq': 'Ndihmë & Pyetje',

    // Command palette additions
    'cmd.action_dashboard': 'Shko te Pulti',
    'cmd.action_settings': 'Cilësimet',
    'cmd.action_students': 'Menaxho Studentët',
    'cmd.action_finance': 'Shiko Financën',
    'cmd.action_attendance': 'Pjesëmarrja',
    'cmd.action_my_students': 'Studentët e mi',
    'cmd.action_my_classes': 'Klasat e mia',
    'cmd.action_my_grades': 'Notat e mia',
    'cmd.action_my_invoices': 'Faturat e mia',
    'cmd.action_my_profile': 'Profili im',

    // Students manual enrollment form
    'students.manual_enrollment': 'Regjistrim Manual',
    'students.manual_enrollment_desc': 'Krijo dhe aktivizo menjëherë një llogari studenti.',
    'students.first_name_req': 'Emri *',
    'students.last_name_req': 'Mbiemri *',
    'students.parent_first_name_req': 'Emri i Prindit *',
    'students.email_req': 'Adresa e Emailit *',
    'students.phone_req': 'Numri i Telefonit *',
    'students.secondary_phone_opt': 'Telefon Dytësor (Opsional)',
    'students.location_req': 'Vendndodhja *',
    'students.initial_password': 'Fjalëkalimi Fillestar *',
    'students.password_hint': 'Studentët duhet ta ndryshojnë këtë fjalëkalim në hyrjen e parë.',
    'students.select_degree_req': 'Zgjidh Diplomën *',
    'students.select_class_req': 'Zgjidh Klasën *',
    'students.select_degree_first': 'Zgjidh diplomën fillimisht',
    'students.loading_classes': 'Duke ngarkuar klasat...',
    'students.select_class_ph': 'Zgjidh Klasën',
    'students.select_location': 'Zgjidh Vendndodhjen',
    'students.select_degree_ph': 'Zgjidh Diplomën',
    'students.enrollment_success': 'Regjistrimi u Krye me Sukses',
    'students.enrollment_success_msg': 'është regjistruar dhe llogaria e tyre është aktive.',
    'students.temp_password': 'Fjalëkalim i përkohshëm:',
    'students.password_change_hint': "Studentit do t'i kërkohet të ndryshojë këtë fjalëkalim në hyrjen e parë.",
    'students.enroll_another': 'Regjistro Tjetër',
    'students.back_to_list': 'Kthehu te Studentët',
    'students.enrollment_failed': 'Regjistrimi dështoi. Ju lutemi provoni përsëri.',
    'students.no_classes_found': 'Nuk u gjetën klasa',
    'students.all_locations': 'Të gjitha Vendndodhjet',
    'students.import_csv': 'Importo CSV',
    'students.importing': 'Duke importuar...',
    'students.enroll_student': 'Regjistro Studentin',
    'students.enrolling': 'Duke regjistruar...',
    'students.err_first_name': 'Emri është i detyrueshëm.',
    'students.err_last_name': 'Mbiemri është i detyrueshëm.',
    'students.err_parent': 'Emri i prindit është i detyrueshëm.',
    'students.err_email': 'Ju lutemi vendosni një adresë emaili të vlefshme.',
    'students.err_phone': 'Numri i telefonit është i detyrueshëm.',
    'students.err_location': 'Ju lutemi zgjidhni një vendndodhje.',
    'students.err_program': 'Ju lutemi zgjidhni një diplomë.',
    'students.err_class': 'Ju lutemi zgjidhni një klasë për këtë diplomë.',

    // Programs page (admin)
    'programs.degrees_title': 'Diplomat',
    'programs.degrees_desc': 'Menaxho diplomat, krijo klasa dhe cakto mësues & studentë.',
    'programs.new_degree': 'Diplomë e Re',
    'programs.empty': 'Asnjë diplomë nuk është krijuar ende.',
    'programs.edit_degree': 'Ndrysho Diplomën',
    'programs.degree_name_req': 'Emri i Diplomës *',
    'programs.degree_name_ph': 'p.sh., Zhvillim Web',
    'programs.description': 'Përshkrimi',
    'programs.description_ph': 'Përshkrim i shkurtër i diplomës...',
    'programs.duration_mo': 'Kohëzgjatja (muaj)',
    'programs.price_eur': 'Çmimi (€)',
    'programs.capacity': 'Kapaciteti',
    'programs.saving': 'Duke ruajtur…',
    'programs.create_degree': 'Krijo Diplomën',
    'programs.save_changes': 'Ruaj Ndryshimet',
    'programs.manage_classes': 'Menaxho klasat për këtë diplomë',
    'programs.new_class': 'Klasë e Re',
    'programs.col_class_name': 'Emri i Klasës',
    'programs.col_teacher': 'Mësuesi',
    'programs.col_students_num': 'Numri i Studentëve',
    'programs.col_schedule': 'Orari',
    'programs.col_degree': 'Diploma',
    'programs.col_action': 'Veprimi',
    'programs.edit': 'Ndrysho',
    'programs.remove': 'Hiq',
    'programs.cancel_edit': 'Anulo Editimin',
    'programs.edit_class': 'Ndrysho Klasën',
    'programs.no_teacher': 'Asnjë mësues i caktuar',
    'programs.weekly_sessions': 'Seancat Javore',
    'programs.enrolled_students': 'Studentët e Regjistruar',
    'programs.add_student': 'Shto Student',
    'programs.no_students': 'Asnjë student i regjistruar ende',
    'programs.create_class': 'Krijo Klasën',
    'programs.class_title': 'Titulli i Klasës',
    'programs.assign_teacher': 'Cakto Mësuesi',
    'programs.add_session': 'Shto Seancë',
    'programs.select_class': 'Zgjidh një klasë…',
    'programs.available_students': 'Studentët e Disponueshëm',
    'programs.no_available': 'Asnjë student i disponueshëm',
    'programs.save_class': 'Ruaj Klasën',
    'programs.select_teacher': 'Zgjidh Mësuesin',
    'programs.no_classes_degree': 'Asnjë klasë e gjetur për këtë diplomë...',
    'programs.back_to_classes': '? Kthehu te Klasat',
    'programs.day_monday': 'E Hënë',
    'programs.day_tuesday': 'E Martë',
    'programs.day_wednesday': 'E Mërkurë',
    'programs.day_thursday': 'E Enjte',
    'programs.day_friday': 'E Premte',
    'programs.day_saturday': 'E Shtunë',
    'programs.day_sunday': 'E Diel',
    'programs.duration_label': 'Kohëzgjatja: {n} muaj',
    'programs.price_label': 'Çmimi: €{n}',
    'programs.capacity_label': 'Kapaciteti: {n} studentë',
    'programs.not_assigned': 'Nuk është caktuar',
    'programs.select_teacher_ph': 'Zgjidhni një mësues...',
    'programs.creating': 'Duke krijuar...',
    'programs.class_title_ph': 'p.sh., Web Dev - Grupi 1',
    'programs.no_classes': 'Nuk ka klasa të krijuara ende',
    'programs.empty_hint': 'Nuk ka diploma të krijuara ende. Klikoni "Diplomë e Re" për të filluar.',

    // Registration applications additions
    'registrations.all': 'Të gjitha',
    'registrations.pending_filter': 'Në Pritje',
    'registrations.approved_filter': 'Miratuar',
    'registrations.rejected_filter': 'Refuzuar',
    'registrations.archived': 'Arkivuar',
    'registrations.archive': 'Arkivo',
    'registrations.unarchive': 'Çarkivo',
    'registrations.applied': 'Aplikoi:',
    'registrations.secondary_phone': 'Telefon Dytësor',
    'registrations.location': 'Vendndodhja',
    'registrations.id_document': 'Dokument Identiteti',
    'registrations.view_document': 'Shiko Dokumentin',
    'registrations.date_of_birth': 'Data e Lindjes',
    'registrations.address': 'Adresa',
    'registrations.emergency_contact': 'Kontakt Urgjence',
    'registrations.emergency_phone': 'Telefon Urgjence',
    'registrations.specialization': 'Specializimi',
    'registrations.qualifications': 'Kualifikimet',
    'registrations.experience': 'Vite Eksperience',
    'registrations.years': 'vite',
    'registrations.admin_notes': 'Shënime Administratori',
    'registrations.assign_class': 'Cakto në Klasë',
    'registrations.loading_classes': 'Duke ngarkuar klasat…',
    'registrations.no_classes': 'Asnjë klasë e gjetur për këtë diplomë...',
    'registrations.select_class': 'Zgjidh një klasë…',
    'registrations.this_app_archived': 'Ky aplikim është arkivuar. Çarkivimi do ta rivendosë në statusin në pritje.',
    'registrations.no_applications': 'Asnjë aplikim nuk u gjet.',
    'registrations.failed_approve': 'Dështoi miratimi i aplikimit',
    'registrations.failed_reject': 'Dështoi refuzimi i aplikimit',
    'registrations.failed_archive': 'Dështoi arkivimi i aplikimit',
    'registrations.failed_unarchive': 'Dështoi çarkivimi i aplikimit',

    // Settings additions
    'settings.platform': 'Cilësimet e Platformës',
    'settings.file_too_large': 'Skedari është shumë i madh. Maksimumi 2 MB.',
    'settings.file_type': 'Lejohen vetëm skedarë JPG, PNG, GIF ose WebP.',
    'settings.upload_success': 'Foto e profilit u ngarkua.',
    'settings.upload_failed': 'Ngarkimi dështoi.',
    'settings.pw_too_short': 'Fjalëkalimi duhet të jetë të paktën 6 karaktere.',
    'settings.pw_mismatch': 'Fjalëkalimet nuk përputhen.',
    'settings.profile_saved': 'Profili u ruajt.',
    'settings.platform_saved': 'Cilësimet e platformës u ruajtën.',
    'settings.save_failed': 'Ruajtja dështoi.',
    'settings.profile_section': 'Profili im',
    'settings.profile_desc': 'Menaxho informacionin tënd personal dhe preferencat.',
    'settings.email_username': 'Email (Emri i Përdoruesit)',
    'settings.file_hints': 'JPG, PNG, GIF ose WebP · Max 2 MB',
    'settings.change_password': 'Ndrysho Fjalëkalimin',
    'settings.new_password': 'Fjalëkalim i Ri',
    'settings.confirm_password': 'Konfirmo Fjalëkalimin',
    'settings.password_hint': 'Minimum 6 karaktere. Lëre bosh për të mbajtur fjalëkalimin aktual.',
    'settings.logo_url': 'URL e Logos',
    'settings.logo_hint': 'Madhësia e rekomanduar: 512x512px (PNG ose SVG)',
    'settings.contact_info': 'Informacion Kontakti',
    'settings.primary_phone': 'Telefon Kryesor',
    'settings.secondary_phone': 'Telefon Dytësor',
    'settings.open_hours': 'Orët e Punës',
    'settings.address': 'Adresa',
    'settings.data_export': 'Eksportimi i të Dhënave',
    'settings.data_export_desc': 'Shkarkoni të dhënat e institucionit tuaj si skedarë CSV.',
    'settings.export_profiles': 'Profilet e Përdoruesve',
    'settings.export_enrollments': 'Regjistrimet e Studentëve',
    'settings.export_attendance': 'Të Dhënat e Pjesëmarrjes',
    'settings.export_invoices': 'Faturat',
    'settings.export_grades': 'Notat',
    'settings.upload_photo': 'Ngarko Foto',
    'settings.uploading': 'Duke ngarkuar…',
    'settings.no_data_found': 'Asnjë të dhënë u gjet.',
    'settings.exported': 'Eksportuar me sukses.',
    'settings.export_failed': 'Eksportimi dështoi.',
    'settings.messages': 'Shabllonet e Mesazheve',
    'settings.messages_desc': 'Personalizoni njoftimet SMS dërguar studentëve dhe stafit.',
    'settings.sms_templates': 'Shabllonet SMS',
    'settings.template_vars': 'Variablat e disponueshme:',
    'settings.template_saved': 'Shablloni u ruajt!',
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}


