import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'AL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.students': 'Students',
    'nav.attendance': 'Attendance',
    'nav.finance': 'Finance',
    'nav.settings': 'Settings',
    'nav.quizzes': 'Quizzes & Events',
    'nav.my_students': 'My Students',
    'nav.my_portal': 'My Portal',
    'nav.grades': 'Grades',
    'nav.invoices': 'Invoices',
    'nav.main_menu': 'Main Menu',
    'nav.system': 'System',
    'nav.logout': 'Logout',
    
    // Header
    'header.search': 'Search students, programs, or invoices...',
    'header.new_enrollment': 'New Enrollment',
    'header.new': 'New',
    
    // Roles
    'role.admin': 'System Admin',
    'role.teacher': 'Teacher',
    'role.student': 'Student',
    
    // Dashboard
    'dash.overview': 'Overview',
    'dash.overview_desc': "Here's what's happening at Future Minds Academy today.",
    'dash.total_students': 'Total Students',
    'dash.active_programs': 'Active Programs',
    'dash.avg_attendance': 'Avg. Attendance',
    'dash.monthly_revenue': 'Monthly Revenue',
    'dash.recent_enrollments': 'Recent Enrollments',
    'dash.view_all': 'View All',
    'dash.quick_actions': 'Quick Actions',
    'dash.generate_invoice': 'Generate Invoice',
    'dash.record_attendance': 'Record Attendance',
    'dash.add_program': 'Add Program',

    // Common Table Headers
    'table.student': 'Student',
    'table.program': 'Program',
    'table.status': 'Status',
    'table.date': 'Date',
    'table.payment': 'Payment',
    'table.action': 'Action',

    // Statuses
    'status.active': 'Active',
    'status.pending': 'Pending',
    'status.suspended': 'Suspended',
    'status.graduated': 'Graduated',
    'status.paid': 'Paid',
    'status.unpaid': 'Unpaid',
    'status.partial': 'Partial',
    'status.present': 'Present',
    'status.absent': 'Absent',
    'status.late': 'Late',

    // Students Page
    'students.title': 'Manage Students',
    'students.desc': 'View, filter, and manage student profiles, admissions, and records.',
    'students.add_new': 'Add Student',
    'students.search': 'Search students by name, ID, or email...',
    'students.filter': 'Filter',
    'students.all_programs': 'All Programs',
    'students.all_statuses': 'All Statuses',
    'students.enrollment_date': 'Enrollment Date',
    'students.new_registration': 'New Student Registration',
    'students.new_registration_desc': 'Register a new student and generate their contract.',
    'students.cancel': 'Cancel',
    'students.first_name': 'First Name',
    'students.last_name': 'Last Name',
    'students.email': 'Email Address',
    'students.phone': 'Phone Number',
    'students.parent_phone': "Parent's Phone (Optional)",
    'students.gender': 'Gender',
    'students.select_gender': 'Select Gender',
    'students.male': 'Male',
    'students.female': 'Female',
    'students.other': 'Other',
    'students.select_program': 'Select Program',
    'students.doc_upload': 'Document Upload',
    'students.drag_drop': 'Drag and drop documents here, or click to browse',
    'students.doc_types': 'ID, Photo, Certificates (PDF, JPG, PNG)',
    'students.save_draft': 'Save as Draft',
    'students.register': 'Register Student',

    // Attendance Page
    'attendance.title': 'Attendance Overview',
    'attendance.desc': 'Monitor student participation across all programs.',
    'attendance.calendar': 'Calendar',
    'attendance.daily_list': 'Daily List',
    'attendance.overall': 'Overall Attendance',
    'attendance.late_today': 'Late Arrivals Today',
    'attendance.low_participation': 'Low Participation Alerts',
    'attendance.search': 'Search students or programs...',
    'attendance.student_info': 'Student Info',
    'attendance.overall_percent': 'Overall %',
    'attendance.today_status': "Today's Status",

    // Finance Page
    'finance.title': 'Financial Overview',
    'finance.desc': 'Manage invoices, track payments, and monitor revenue.',
    'finance.create_invoice': 'Create Invoice',
    'finance.total_collected': 'Total Collected',
    'finance.pending_payments': 'Pending Payments',
    'finance.overdue_amount': 'Overdue Amount',
    'finance.search': 'Search invoices by ID or student name...',
    'finance.invoice_id': 'Invoice ID',
    'finance.amount': 'Amount',
    'finance.due_date': 'Due Date',

    // Teacher Dashboard
    'teacher.portal': 'Teacher Portal',
    'teacher.desc': 'Manage your classes, assignments, and student progress.',
    'teacher.create_quiz': 'Create Quiz / Event',
    'teacher.upcoming_classes': 'Upcoming Classes',
    'teacher.avg_class_grade': 'Avg. Class Grade',
    'teacher.active_quizzes': 'Active Quizzes',
    'teacher.recent_quizzes': 'Recent Quizzes & Assignments',
    'teacher.title_program': 'Title & Program',
    'teacher.submissions': 'Submissions',
    'teacher.due_date': 'Due Date',
    'teacher.grade_submissions': 'Grade Submissions',
    'teacher.message_class': 'Message Class',
    'teacher.new_quiz': 'New Quiz / Event',
    'teacher.new_quiz_desc': 'Create a new assessment or schedule an event for your classes.',
    'teacher.cancel': 'Cancel',
    'teacher.title': 'Title',
    'teacher.type': 'Type',
    'teacher.select_type': 'Select Type',
    'teacher.quiz': 'Quiz',
    'teacher.assignment': 'Assignment',
    'teacher.event': 'Event',
    'teacher.program': 'Program',
    'teacher.select_program': 'Select Program',
    'teacher.date': 'Date',
    'teacher.time': 'Time',
    'teacher.duration': 'Duration (Minutes)',
    'teacher.max_score': 'Maximum Score',
    'teacher.description': 'Description',
    'teacher.save_draft': 'Save Draft',
    'teacher.publish': 'Publish',

    // Student Dashboard
    'student.welcome': 'Welcome back',
    'student.desc': 'Here is your academic and financial overview.',
    'student.overall_grade': 'Overall Grade',
    'student.attendance': 'Attendance',
    'student.active_courses': 'Active Courses',
    'student.next_payment': 'Next Payment',
    'student.recent_grades': 'Recent Grades & Quizzes',
    'student.assessment': 'Assessment',
    'student.score': 'Score',
    'student.my_invoices': 'My Invoices',

    // New Pages & Modals
    'teacher.total_students': 'Total Students',
    'teacher.avg_grade': 'Average Grade',
    'status.grading': 'Grading',
    'status.completed': 'Completed',
    'status.scheduled': 'Scheduled',
    'nav.announcements': 'Announcements',
    'nav.programs': 'Programs',
    'announcements.title': 'Announcements',
    'announcements.desc': 'Stay updated with the latest news and events.',
    'announcements.new': 'New Announcement',
    'announcements.msg_title': 'Title',
    'announcements.message': 'Message',
    'announcements.audience': 'Target Audience',
    'announcements.publish': 'Publish Announcement',
    'programs.title': 'Programs & Courses',
    'programs.desc': 'Manage academic programs, pricing, and assignments.',
    'programs.new': 'New Program',
    'programs.name': 'Program Name',
    'programs.price': 'Price ($)',
    'programs.duration': 'Duration (Months)',
    'programs.save': 'Save Program',
    'settings.profile': 'Profile Settings',
    'settings.avatar': 'Avatar Image URL',
    'settings.save': 'Save Changes',
    'settings.title': 'System Settings',
    'settings.desc': 'Manage your institution\'s preferences and configurations.',
    'settings.general': 'General',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.data': 'Data & Privacy',
    'settings.inst_profile': 'Institution Profile',
    'settings.inst_name': 'Institution Name',
    'settings.contact_email': 'Contact Email',
    'settings.phone': 'Phone Number',
    'settings.timezone': 'Timezone',
    'settings.branding': 'Branding',
    'settings.change_logo': 'Change Logo',
    'payment.title': 'Payment Instructions',
    'payment.desc': 'To complete this payment, please visit our administration office or contact us via email.',
    'payment.address': 'Address',
    'payment.email': 'Email',
    'payment.close': 'Close',
    'teacher.grade_modal_title': 'Grade Submissions',
    'teacher.grade_modal_desc': 'Enter scores for student submissions.',
    'teacher.save_grades': 'Save Grades',
    'student.overall_avg': 'Overall Average',
    'student.assessments_completed': 'Assessments Completed',
    'student.current_grade': 'Current Grade',
    'student.total_paid': 'Total Paid',
    'student.pending_balance': 'Pending Balance',
    'student.next_due': 'Next Payment Due',
    'student.pay_now': 'Pay Now',
    
    // New Additions (Profile, Export, FAQ, Command Palette)
    'profile.title': 'Student Profile',
    'profile.desc': 'Detailed view of student academic and financial records.',
    'profile.personal_info': 'Personal Information',
    'profile.academic_info': 'Academic Information',
    'profile.financial_info': 'Financial Information',
    'profile.enrollment_date': 'Enrollment Date',
    'profile.program': 'Program',
    'profile.status': 'Status',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.back': 'Back to Students',
    'profile.edit': 'Edit Profile',
    'profile.attendance_rate': 'Attendance Rate',
    'profile.current_grade': 'Current Grade',
    'profile.total_invoiced': 'Total Invoiced',
    'profile.total_paid': 'Total Paid',
    'profile.outstanding_balance': 'Outstanding Balance',
    'action.export': 'Export',
    'action.export_csv': 'Export to CSV',
    'action.export_pdf': 'Export to PDF',
    'faq.title': 'Help & FAQ',
    'faq.search_q': 'How do I search quickly?',
    'faq.search_a': 'Press Cmd + K (or Ctrl+K on Windows) anywhere in the app to open the Command Palette. You can jump to any page instantly.',
    'faq.profile_q': 'How do I view a student\'s full profile?',
    'faq.profile_a': 'Click on any student row in the Students table to open their quick-view panel. From there, you can click "View Full Profile" to see all their details.',
    'faq.export_q': 'Can I export data?',
    'faq.export_a': 'Yes! Look for the "Export" button on the Students, Finance, and Attendance pages to download a CSV or PDF report.',
    'faq.select_q': 'How do I select multiple students?',
    'faq.select_a': 'Use the checkboxes on the left side of the Students table to select multiple records for bulk actions.',
    'cmd.placeholder': 'Type a command or search...',
    'cmd.quick_actions': 'Quick Actions',
    'cmd.no_results': 'No results found for',
    'cmd.navigate': 'to navigate',
    'cmd.close': 'to close',
    'dash.needs_attention': 'Needs Attention',
    'dash.pending_apps': 'Pending Applications',
    'dash.overdue_inv': 'Overdue Invoices',
    'dash.at_risk': 'Students at Risk (Attendance)',
  },
  AL: {
    // Navigation
    'nav.dashboard': 'Pulti',
    'nav.students': 'Studentët',
    'nav.attendance': 'Pjesëmarrja',
    'nav.finance': 'Financa',
    'nav.settings': 'Cilësimet',
    'nav.quizzes': 'Kuize & Evente',
    'nav.my_students': 'Studentët e mi',
    'nav.my_portal': 'Portali im',
    'nav.grades': 'Notat',
    'nav.invoices': 'Faturat',
    'nav.main_menu': 'Menyja Kryesore',
    'nav.system': 'Sistemi',
    'nav.logout': 'Dil',
    
    // Header
    'header.search': 'Kërko studentë, programe, ose fatura...',
    'header.new_enrollment': 'Regjistrim i Ri',
    'header.new': 'I Ri',
    
    // Roles
    'role.admin': 'Administrator',
    'role.teacher': 'Mësues',
    'role.student': 'Student',
    
    // Dashboard
    'dash.overview': 'Përmbledhje',
    'dash.overview_desc': "Ja çfarë po ndodh në Future Minds Academy sot.",
    'dash.total_students': 'Totali i Studentëve',
    'dash.active_programs': 'Programe Aktive',
    'dash.avg_attendance': 'Pjesëmarrja Mesatare',
    'dash.monthly_revenue': 'Të Ardhurat Mujore',
    'dash.recent_enrollments': 'Regjistrimet e Fundit',
    'dash.view_all': 'Shiko të Gjitha',
    'dash.quick_actions': 'Veprime të Shpejta',
    'dash.generate_invoice': 'Gjenero Faturë',
    'dash.record_attendance': 'Shëno Pjesëmarrjen',
    'dash.add_program': 'Shto Program',

    // Common Table Headers
    'table.student': 'Studenti',
    'table.program': 'Programi',
    'table.status': 'Statusi',
    'table.date': 'Data',
    'table.payment': 'Pagesa',
    'table.action': 'Veprimi',

    // Statuses
    'status.active': 'Aktiv',
    'status.pending': 'Në Pritje',
    'status.suspended': 'Pezulluar',
    'status.graduated': 'I Diplomuar',
    'status.paid': 'Paguar',
    'status.unpaid': 'E Papaguar',
    'status.partial': 'Pjesërisht',
    'status.present': 'Prezent',
    'status.absent': 'Mungesë',
    'status.late': 'Vonesë',

    // Students Page
    'students.title': 'Menaxho Studentët',
    'students.desc': 'Shiko, filtro dhe menaxho profilet e studentëve, pranimet dhe të dhënat.',
    'students.add_new': 'Shto Student',
    'students.search': 'Kërko studentë sipas emrit, ID, ose emailit...',
    'students.filter': 'Filtro',
    'students.all_programs': 'Të Gjitha Programet',
    'students.all_statuses': 'Të Gjitha Statuset',
    'students.enrollment_date': 'Data e Regjistrimit',
    'students.new_registration': 'Regjistrim i Ri Studenti',
    'students.new_registration_desc': 'Regjistro një student të ri dhe gjenero kontratën e tyre.',
    'students.cancel': 'Anulo',
    'students.first_name': 'Emri',
    'students.last_name': 'Mbiemri',
    'students.email': 'Adresa e Emailit',
    'students.phone': 'Numri i Telefonit',
    'students.parent_phone': "Telefoni i Prindit (Opsionale)",
    'students.gender': 'Gjinia',
    'students.select_gender': 'Zgjidh Gjininë',
    'students.male': 'Mashkull',
    'students.female': 'Femër',
    'students.other': 'Tjetër',
    'students.select_program': 'Zgjidh Programin',
    'students.doc_upload': 'Ngarkimi i Dokumenteve',
    'students.drag_drop': 'Tërhiq dhe lësho dokumentet këtu, ose kliko për të shfletuar',
    'students.doc_types': 'ID, Foto, Çertifikata (PDF, JPG, PNG)',
    'students.save_draft': 'Ruaj si Draft',
    'students.register': 'Regjistro Studentin',

    // Attendance Page
    'attendance.title': 'Përmbledhja e Pjesëmarrjes',
    'attendance.desc': 'Monitoro pjesëmarrjen e studentëve në të gjitha programet.',
    'attendance.calendar': 'Kalendari',
    'attendance.daily_list': 'Lista Ditore',
    'attendance.overall': 'Pjesëmarrja e Përgjithshme',
    'attendance.late_today': 'Vonesat Sot',
    'attendance.low_participation': 'Alarme për Pjesëmarrje të Ulët',
    'attendance.search': 'Kërko studentë ose programe...',
    'attendance.student_info': 'Info e Studentit',
    'attendance.overall_percent': '% e Përgjithshme',
    'attendance.today_status': "Statusi i Sotëm",

    // Finance Page
    'finance.title': 'Përmbledhja Financiare',
    'finance.desc': 'Menaxho faturat, gjurmo pagesat dhe monitoro të ardhurat.',
    'finance.create_invoice': 'Krijo Faturë',
    'finance.total_collected': 'Totali i Mbledhur',
    'finance.pending_payments': 'Pagesat në Pritje',
    'finance.overdue_amount': 'Shuma e Vonuar',
    'finance.search': 'Kërko fatura sipas ID ose emrit të studentit...',
    'finance.invoice_id': 'ID e Faturës',
    'finance.amount': 'Shuma',
    'finance.due_date': 'Data e Skadimit',

    // Teacher Dashboard
    'teacher.portal': 'Portali i Mësuesit',
    'teacher.desc': 'Menaxho klasat, detyrat dhe progresin e studentëve.',
    'teacher.create_quiz': 'Krijo Kuiz / Event',
    'teacher.upcoming_classes': 'Klasat e Ardhshme',
    'teacher.avg_class_grade': 'Nota Mesatare e Klasës',
    'teacher.active_quizzes': 'Kuize Aktive',
    'teacher.recent_quizzes': 'Kuizet & Detyrat e Fundit',
    'teacher.title_program': 'Titulli & Programi',
    'teacher.submissions': 'Dorëzimet',
    'teacher.due_date': 'Data e Skadimit',
    'teacher.grade_submissions': 'Vlerëso Dorëzimet',
    'teacher.message_class': 'Dërgo Mesazh Klasës',
    'teacher.new_quiz': 'Kuiz / Event i Ri',
    'teacher.new_quiz_desc': 'Krijo një vlerësim të ri ose planifiko një event për klasat e tua.',
    'teacher.cancel': 'Anulo',
    'teacher.title': 'Titulli',
    'teacher.type': 'Tipi',
    'teacher.select_type': 'Zgjidh Tipin',
    'teacher.quiz': 'Kuiz',
    'teacher.assignment': 'Detyrë',
    'teacher.event': 'Event',
    'teacher.program': 'Programi',
    'teacher.select_program': 'Zgjidh Programin',
    'teacher.date': 'Data',
    'teacher.time': 'Koha',
    'teacher.duration': 'Kohëzgjatja (Minuta)',
    'teacher.max_score': 'Pikët Maksimale',
    'teacher.description': 'Përshkrimi',
    'teacher.save_draft': 'Ruaj Draft',
    'teacher.publish': 'Publiko',

    // Student Dashboard
    'student.welcome': 'Mirë se u ktheve',
    'student.desc': 'Këtu është përmbledhja juaj akademike dhe financiare.',
    'student.overall_grade': 'Nota e Përgjithshme',
    'student.attendance': 'Pjesëmarrja',
    'student.active_courses': 'Kurse Aktive',
    'student.next_payment': 'Pagesa e Radhës',
    'student.recent_grades': 'Notat & Kuizet e Fundit',
    'student.assessment': 'Vlerësimi',
    'student.score': 'Pikët',
    'student.my_invoices': 'Faturat e Mia',

    // New Pages & Modals
    'teacher.total_students': 'Totali i Studentëve',
    'teacher.avg_grade': 'Nota Mesatare',
    'status.grading': 'Në Vlerësim',
    'status.completed': 'Përfunduar',
    'status.scheduled': 'Planifikuar',
    'nav.announcements': 'Lajmërime',
    'nav.programs': 'Programet',
    'announcements.title': 'Lajmërime',
    'announcements.desc': 'Qëndroni të përditësuar me lajmet dhe eventet e fundit.',
    'announcements.new': 'Lajmërim i Ri',
    'announcements.msg_title': 'Titulli',
    'announcements.message': 'Mesazhi',
    'announcements.audience': 'Audienca',
    'announcements.publish': 'Publiko Lajmërimin',
    'programs.title': 'Programet & Kurset',
    'programs.desc': 'Menaxhoni programet akademike, çmimet dhe caktimet.',
    'programs.new': 'Program i Ri',
    'programs.name': 'Emri i Programit',
    'programs.price': 'Çmimi ($)',
    'programs.duration': 'Kohëzgjatja (Muaj)',
    'programs.save': 'Ruaj Programin',
    'settings.profile': 'Cilësimet e Profilit',
    'settings.avatar': 'URL e Fotos së Profilit',
    'settings.save': 'Ruaj Ndryshimet',
    'settings.title': 'Cilësimet e Sistemit',
    'settings.desc': 'Menaxhoni preferencat dhe konfigurimet e institucionit tuaj.',
    'settings.general': 'Të Përgjithshme',
    'settings.security': 'Siguria',
    'settings.notifications': 'Njoftimet',
    'settings.data': 'Të Dhënat & Privatësia',
    'settings.inst_profile': 'Profili i Institucionit',
    'settings.inst_name': 'Emri i Institucionit',
    'settings.contact_email': 'Emaili i Kontaktit',
    'settings.phone': 'Numri i Telefonit',
    'settings.timezone': 'Zona Kohore',
    'settings.branding': 'Marka',
    'settings.change_logo': 'Ndrysho Logon',
    'payment.title': 'Udhëzimet e Pagesës',
    'payment.desc': 'Për të përfunduar këtë pagesë, ju lutemi vizitoni zyrën tonë të administratës ose na kontaktoni përmes emailit.',
    'payment.address': 'Adresa',
    'payment.email': 'Email',
    'payment.close': 'Mbyll',
    'teacher.grade_modal_title': 'Vlerëso Dorëzimet',
    'teacher.grade_modal_desc': 'Vendosni pikët për dorëzimet e studentëve.',
    'teacher.save_grades': 'Ruaj Notat',
    'student.overall_avg': 'Mesatarja e Përgjithshme',
    'student.assessments_completed': 'Vlerësime të Përfunduara',
    'student.current_grade': 'Nota Aktuale',
    'student.total_paid': 'Totali i Paguar',
    'student.pending_balance': 'Bilanci në Pritje',
    'student.next_due': 'Pagesa e Radhës',
    'student.pay_now': 'Paguaj Tani',
    
    // New Additions (Profile, Export, FAQ, Command Palette)
    'profile.title': 'Profili i Studentit',
    'profile.desc': 'Pamje e detajuar e të dhënave akademike dhe financiare të studentit.',
    'profile.personal_info': 'Informacion Personal',
    'profile.academic_info': 'Informacion Akademik',
    'profile.financial_info': 'Informacion Financiar',
    'profile.enrollment_date': 'Data e Regjistrimit',
    'profile.program': 'Programi',
    'profile.status': 'Statusi',
    'profile.email': 'Emaili',
    'profile.phone': 'Telefoni',
    'profile.address': 'Adresa',
    'profile.back': 'Kthehu te Studentët',
    'profile.edit': 'Ndrysho Profilin',
    'profile.attendance_rate': 'Përqindja e Pjesëmarrjes',
    'profile.current_grade': 'Nota Aktuale',
    'profile.total_invoiced': 'Totali i Faturuar',
    'profile.total_paid': 'Totali i Paguar',
    'profile.outstanding_balance': 'Bilanci i Papaguar',
    'action.export': 'Eksporto',
    'action.export_csv': 'Eksporto në CSV',
    'action.export_pdf': 'Eksporto në PDF',
    'faq.title': 'Ndihmë & Pyetje',
    'faq.search_q': 'Si mund të kërkoj shpejt?',
    'faq.search_a': 'Shtyp Cmd + K (ose Ctrl+K në Windows) kudo në aplikacion për të hapur Paletën e Komandave. Mund të kalosh në çdo faqe menjëherë.',
    'faq.profile_q': 'Si mund ta shoh profilin e plotë të një studenti?',
    'faq.profile_a': 'Kliko në çdo rresht studenti në tabelën e Studentëve për të hapur panelin e tyre të shpejtë. Nga aty, mund të klikosh "Shiko Profilin e Plotë" për të parë të gjitha detajet e tyre.',
    'faq.export_q': 'A mund të eksportoj të dhëna?',
    'faq.export_a': 'Po! Kërko butonin "Eksporto" në faqet e Studentëve, Financës dhe Pjesëmarrjes për të shkarkuar një raport CSV ose PDF.',
    'faq.select_q': 'Si mund të zgjedh disa studentë?',
    'faq.select_a': 'Përdor kutitë e zgjedhjes në anën e majtë të tabelës së Studentëve për të zgjedhur disa rekorde për veprime në grup.',
    'cmd.placeholder': 'Shkruaj një komandë ose kërko...',
    'cmd.quick_actions': 'Veprime të Shpejta',
    'cmd.no_results': 'Nuk u gjetën rezultate për',
    'cmd.navigate': 'për të naviguar',
    'cmd.close': 'për të mbyllur',
    'dash.needs_attention': 'Kërkon Vëmendje',
    'dash.pending_apps': 'Aplikime në Pritje',
    'dash.overdue_inv': 'Fatura të Vonuara',
    'dash.at_risk': 'Studentë në Rrezik (Pjesëmarrja)',
  }
};

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
