ALTER TABLE classes ADD COLUMN IF NOT EXISTS code VARCHAR(8);
ALTER TABLE classes ADD COLUMN IF NOT EXISTS meet_link TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS classes_code_unique ON classes (code) WHERE code IS NOT NULL;
